#!/usr/bin/env python3
"""
Database Migration Helper Script
================================
Safe, verified migration operations for Kinmel Inventory System.

Usage:
    python scripts/db.py migrate          # Apply all pending migrations
    python scripts/db.py rollback         # Rollback one migration
    python scripts/db.py status           # Show current migration status
    python scripts/db.py generate "name"  # Generate new migration (manual review!)
    python scripts/db.py verify           # Verify models match schema
    python scripts/db.py reset            # Drop and recreate (DEV ONLY!)

IMPORTANT:
    Never run 'reset' in production!
    Always review autogenerated migrations before applying.
"""

import argparse
import subprocess
import sys
from pathlib import Path

# Ensure we're in the project root
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def run_alembic(args: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run alembic command from project root."""
    cmd = ["alembic"] + args
    print(f"🔧 Running: {' '.join(cmd)}")
    return subprocess.run(
        cmd,
        cwd=PROJECT_ROOT,
        check=check,
        capture_output=False,
    )


def cmd_migrate(args: argparse.Namespace) -> int:
    """Apply pending migrations."""
    print("📦 Applying database migrations...")
    
    # Show current status first
    run_alembic(["current"], check=False)
    print()
    
    # Apply migrations
    result = run_alembic(["upgrade", args.revision])
    
    if result.returncode == 0:
        print("\n✅ Migrations applied successfully!")
        run_alembic(["current"], check=False)
    else:
        print("\n❌ Migration failed!")
        
    return result.returncode


def cmd_rollback(args: argparse.Namespace) -> int:
    """Rollback migrations."""
    print("⏪ Rolling back migrations...")
    
    # Show current status
    run_alembic(["current"], check=False)
    print()
    
    # Downgrade
    revision = f"-{args.steps}" if args.steps else "-1"
    result = run_alembic(["downgrade", revision])
    
    if result.returncode == 0:
        print(f"\n✅ Rolled back {args.steps or 1} migration(s)!")
        run_alembic(["current"], check=False)
    else:
        print("\n❌ Rollback failed!")
        
    return result.returncode


def cmd_status(args: argparse.Namespace) -> int:
    """Show migration status."""
    print("📊 Migration Status")
    print("=" * 40)
    
    print("\n🔹 Current revision:")
    run_alembic(["current"], check=False)
    
    print("\n🔹 Migration history:")
    run_alembic(["history", "--verbose"], check=False)
    
    return 0


def cmd_generate(args: argparse.Namespace) -> int:
    """Generate a new migration."""
    if not args.message:
        print("❌ Please provide a migration message!")
        print("   Example: python scripts/db.py generate 'add_supplier_table'")
        return 1
    
    print(f"🔨 Generating migration: {args.message}")
    print()
    print("⚠️  IMPORTANT: Autogenerate is a STARTING POINT, not the final result!")
    print("    You MUST review the generated migration for:")
    print("    - Correct table/column creation order")
    print("    - Proper constraint names")
    print("    - Data preservation in column changes")
    print("    - Correct downgrade operations")
    print()
    
    result = run_alembic([
        "revision",
        "--autogenerate",
        "-m", args.message,
    ])
    
    if result.returncode == 0:
        print("\n✅ Migration generated!")
        print("📝 NEXT STEPS:")
        print("   1. Review the generated migration file")
        print("   2. Verify CHECK constraints are correct")
        print("   3. Test downgrade path")
        print("   4. Commit to version control")
    else:
        print("\n❌ Generation failed!")
        
    return result.returncode


def cmd_verify(args: argparse.Namespace) -> int:
    """Verify models match current schema."""
    print("🔍 Verifying model-schema consistency...")
    print()
    
    # Generate a migration to see what's different
    # If nothing is generated, models match schema
    result = run_alembic([
        "revision",
        "--autogenerate",
        "-m", "_verify_check",
    ], check=False)
    
    # Check if migration was generated
    versions_dir = PROJECT_ROOT / "alembic" / "versions"
    verify_files = list(versions_dir.glob("*_verify_check.py"))
    
    if verify_files:
        # Read the file to check if it's empty
        migration_file = verify_files[0]
        content = migration_file.read_text()
        
        # Check if upgrade/downgrade are just 'pass'
        if "pass" in content and content.count("pass") >= 2:
            print("✅ Models match database schema!")
            migration_file.unlink()  # Delete the empty migration
            return 0
        else:
            print("⚠️  Schema drift detected!")
            print(f"   Review generated migration: {migration_file}")
            print("   If changes are expected, rename and commit it.")
            print("   If unexpected, investigate the drift.")
            return 1
    else:
        if result.returncode == 0:
            print("✅ Models match database schema!")
            return 0
        else:
            print("❌ Verification failed - could not compare schemas")
            return 1


def cmd_reset(args: argparse.Namespace) -> int:
    """Reset database (DEV ONLY!)."""
    from src.core.config import get_settings
    
    settings = get_settings()
    
    if settings.is_production:
        print("🚫 REFUSING to reset production database!")
        print("   This command is only for development environments.")
        return 1
    
    if not args.force:
        print("⚠️  WARNING: This will DELETE ALL DATA!")
        print("   Only use in development environments.")
        response = input("   Type 'yes' to confirm: ")
        if response.lower() != "yes":
            print("   Cancelled.")
            return 1
    
    print("🗑️  Resetting database...")
    
    # Downgrade to base (nothing)
    result = run_alembic(["downgrade", "base"])
    if result.returncode != 0:
        print("❌ Downgrade failed!")
        return result.returncode
    
    # Upgrade to head
    result = run_alembic(["upgrade", "head"])
    if result.returncode != 0:
        print("❌ Upgrade failed!")
        return result.returncode
    
    print("\n✅ Database reset complete!")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Database migration helper for Kinmel Inventory",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # migrate
    migrate_parser = subparsers.add_parser("migrate", help="Apply pending migrations")
    migrate_parser.add_argument(
        "--revision", "-r",
        default="head",
        help="Target revision (default: head)",
    )
    migrate_parser.set_defaults(func=cmd_migrate)
    
    # rollback
    rollback_parser = subparsers.add_parser("rollback", help="Rollback migrations")
    rollback_parser.add_argument(
        "--steps", "-n",
        type=int,
        default=1,
        help="Number of migrations to rollback (default: 1)",
    )
    rollback_parser.set_defaults(func=cmd_rollback)
    
    # status
    status_parser = subparsers.add_parser("status", help="Show migration status")
    status_parser.set_defaults(func=cmd_status)
    
    # generate
    generate_parser = subparsers.add_parser("generate", help="Generate new migration")
    generate_parser.add_argument(
        "message",
        nargs="?",
        help="Migration description (snake_case)",
    )
    generate_parser.set_defaults(func=cmd_generate)
    
    # verify
    verify_parser = subparsers.add_parser("verify", help="Verify models match schema")
    verify_parser.set_defaults(func=cmd_verify)
    
    # reset
    reset_parser = subparsers.add_parser("reset", help="Reset database (DEV ONLY!)")
    reset_parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Skip confirmation prompt",
    )
    reset_parser.set_defaults(func=cmd_reset)
    
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
