"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Migration Guidelines:
--------------------
1. Always test both upgrade AND downgrade paths
2. Never modify data in schema migrations (use separate data migrations)
3. Add CHECK constraints for domain invariants
4. Consider index impact on write performance
5. For large tables, consider concurrent index creation

Safety Checklist:
-----------------
[ ] Reviewed autogenerated code (if applicable)
[ ] Downgrade restores original state
[ ] No data loss in rollback
[ ] Constraints match model definitions
[ ] Indexes support expected queries
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    """Apply schema changes."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Revert schema changes."""
    ${downgrades if downgrades else "pass"}
